using System;
using System.Collections.Generic;
using MyGames;
using UnityEngine;
using Debug = MyGames.Debug;

namespace nostra.booboogames.hangoutconcert
{
    public class CustomizationManager : XPEarningMethod
    {
        [SerializeField] private List<GameObject> topsList;
        [SerializeField] private List<GameObject> pantsList;
        [SerializeField] private List<GameObject> hairStylesList;
        [SerializeField] private List<GameObject> shoesList;

        public static event Action OnAutoGeneratedOutfit;

        protected override void Start()
        {
            xpReward = GameManager.ClothesStylingBoothXpReward;
            xpEarningCooldown = GameManager.ClothesStylingBoothXpEarningCooldown;

            base.Start();
        }

        private void DisableAllItemsInList(List<GameObject> objectsList)
        {
            foreach (GameObject gameObject in objectsList)
            {
                gameObject.SetActive(false);
            }
        }

        public void AutoGenerateOutfit()
        {
            DisableAllItemsInList(topsList);
            DisableAllItemsInList(shoesList);
            DisableAllItemsInList(pantsList);
            DisableAllItemsInList(hairStylesList);

            int topIndex = Utils.GetRandomIndexFromList(topsList);
            int pantIndex = Utils.GetRandomIndexFromList(pantsList);
            int hairStyleIndex = Utils.GetRandomIndexFromList(hairStylesList);
            int shoeIndex = Utils.GetRandomIndexFromList(shoesList);

            topsList[topIndex].SetActive(true);
            pantsList[pantIndex].SetActive(true);
            hairStylesList[hairStyleIndex].SetActive(true);
            shoesList[shoeIndex].SetActive(true);

            if (canEarnXp)
            {
                OnAutoGeneratedOutfit?.Invoke();
                EarnXp(xpReward);
                StartCoroutine(StartCooldown());
            }
            else
            {
                // maybe add a ui prompt notifying the player that they can't receive any xp when the cooldown is active
            }
        }
    }
}
