using System;
using Debug = MyGames.Debug;

namespace nostra.booboogames.hangoutconcert
{
    public class OutfitStylingBooth : Interactable
    {
        public static event Action OnEnterOutfitStylingBooth;

        protected override void Start()
        {
            base.Start();

            CustomizationManager.OnAutoGeneratedOutfit += CustomizationManager_OnAutoGeneratedOutfit;
        }

        private void CustomizationManager_OnAutoGeneratedOutfit()
        {
            isPlayerInteracting = false;
        }

        private void OnDestroy()
        {
            CustomizationManager.OnAutoGeneratedOutfit -= CustomizationManager_OnAutoGeneratedOutfit;
        }

        public override void Interact()
        {
            base.Interact();

            OnEnterOutfitStylingBooth?.Invoke();
        }
    }
}
